services:
  postgres:
    image: postgres:16
    container_name: soldorado-postgres
    environment:
      POSTGRES_DB: elsoldorado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mathi2707
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
