spring.application.name=soldorado-api
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/elsoldorado}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:missu741}
spring.datasource.driver-class-name=org.postgresql.Driver
    
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:el-sol-dorado-super-secret-key-para-firmar-jwt-version-2026}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:120}

management.endpoints.web.exposure.include=health,info
