spring.application.name=app

# Conclusión única para la aplicación y Flyway
spring.datasource.url=jdbc:postgresql://localhost:5432/elsoldorado
spring.datasource.username=postgres
spring.datasource.password=missu741

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway simplificado
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
